### ISSUE TITLE
星标的排序可不可以按照更新时间从上到下排列？

### ISSUE THREAD

**Issue by wclmgcd** [GeekHubClient/GeekHub-Feedback#4]
星标的排序可不可以按照更新时间从上到下排列？

运行环境: iPhone XR - iOS13.3.1 - v1.3.1(29)

**Comment by evanzhou1989** [comment]
后续版本会增加排序方式选择

**Comment by evanzhou1989** [comment]
查了下目前官方开放的GraphQL V4版本的API中只能根据STARRED_AT排序，无法根据更新时间排序┓( ´∀` )┏，所以暂时先关闭issue了，后期如果官方有更新，会第一时间同步。
