### ISSUE TITLE
底部栏的“Trending”和“Stars”里的显示内容能不能和“News”一样，标题和下面的内容对齐不要和图标对齐啊？

总感觉左重右轻的感觉，不美观！
望改进！

### ISSUE THREAD

**Issue by whalien520** [GeekHubClient/GeekHub-Feedback#5]
底部栏的“Trending”和“Stars”里的显示内容能不能和“News”一样，标题和下面的内容对齐不要和图标对齐啊？

总感觉左重右轻的感觉，不美观！
望改进！

Environment: iPhone XS Max CN - iOS13.3.1 - v1.3.2(30)

**Comment by evanzhou1989** [comment]
事实上前几个版本就是和News一样的，最近几个版本才改成现在这个样子，之前是感觉左边头像完全占据一部分空间有点浪费。其实我个人是比较倾向你的看法的，下个版本改回去。感谢反馈~

**Comment by evanzhou1989** [comment]
V1.3.3已更新
