### ISSUE TITLE
大佬，可以改回最先的那个图标吗？强迫症啊

### ISSUE THREAD

**Issue by wclmgcd** [GeekHubClient/GeekHub-Feedback#7]
大佬，可以改回最先的那个图标吗？强迫症啊

运行环境: iPhone XR - iOS13.3.1 - v1.4.0(89)

**Comment by evanzhou1989** [comment]
进入设置->图标，最底下那个就是最先的图标，可以自己设置下。不过新图标看习惯了应该也还行吧😂
