### ISSUE TITLE
添加对 submodule 的支持

### ISSUE THREAD

**Issue by amorphobia** [GeekHubClient/GeekHub-Feedback#8]
目前版本的 GeekHub 将 submodule 当作一个文件，且无法打开。

例子：
https://github.com/rime/weasel
这个仓库中包含 submodule 
https://github.com/rime/librime
https://github.com/rime/plum

在 App 里显示为 librime 和 plum, 不能打开。

**Comment by evanzhou1989** [comment]
看了下是因为目前 GitHub API 还未支持 submodule，我看了下 GitHub 官方 App 也一样。等 GitHub API 支持后我再处理这个，暂时搞不定～

**Comment by amorphobia** [comment]
@evanzhou1989 

对于无法打开的文件，是否可以提示在 safari 中打开？

（不知 github 网站是如何实现的…）

**Comment by evanzhou1989** [comment]
@amorphobia V1.5.0已支持submodule
